### ISSUE TITLE
{string}.fixLinks() doesnt work

### ISSUE THREAD

**Issue by kerbybit** [kerbybit/ChatTriggers#49]

**Comment by kerbybit** [comment]
Seems to work fine
Might be an issue with multiple triggers on one chat or a string getting overwritten by another trigger

**Comment by WolfMasterRJ** [comment]
Not sure what you meant by issue with multiple triggers but it's still broken for me.

I do "chat {string[customprefix]}{string[name]} {string[message]}.fixlinks()"
However when the message has links, it'll print the unmodified message without customprefix
