### ISSUE TITLE
[SUGGESTION] onChatEvent trigger type

### ISSUE THREAD

**Issue by WolfMasterRJ** [kerbybit/ChatTriggers#52]
Trigger type that intercepts all messages about to be shown in chat using the "chat" event. The cancel event would stop the message from passing through. Maybe {msg} would return the message being passed through. 

Example:

> trigger onChatEvent(name) {
    if ({list[messagesToStop]}.has({msg}))
      cancel
    end
}`

**Comment by kerbybit** [comment]
Already a thing
```
trigger onChat(this doesnt matter, its just the name) {
  if ({list[messagesToStop]}.has({msg})
    cancel
  end
}
```
This will run on every chat message

**Comment by kerbybit** [comment]
nvm I just read it for real this time
There is no way of catching chat before it is sent from the client to the server with forge atm and there might not ever be :(
