### ISSUE TITLE
[BUG/SUGGESTION] Attach clickables to strings

### ISSUE THREAD

**Issue by WolfMasterRJ** [kerbybit/ChatTriggers#54]
I want to be able to suffix/prefix clickables to strings so it can outputted in chat later.

> trigger other(testclick) {
  do {string[test2]}.set(Base Text)
  do {string[test2]}.set({string[test2]}.suffix(clickable(&c[Hi],suggest_command,hi,&cHi)))
  do {string[test2]}.set({string[test2]}.suffix(clickable(&c[Bye],suggest_command,bye,&cBye)))
  chat {string[test2]}
}

**Comment by kerbybit** [comment]
probably  wont happen until the back end rewrite. There are a lot of reasons why that can never work in the current state of things
