### ISSUE TITLE
[SUGGESTION] {speed} built in string

### ISSUE THREAD

**Issue by WolfMasterRJ** [kerbybit/ChatTriggers#55]
Just returns the speed the player is going at. X coordinates and Z coordinates only so ignore Y.

Made it in code too :) 

> trigger onClientTick 20(speed) {
  do {string[deltax]}.set({exactX}.-({string[oldX]}))
  do {string[deltaz]}.set({exactZ}.-({string[oldZ]}))
  do {string[distance]}.set({string[deltax]}.power(2))
  do {string[distance]}.+({string[deltaz]}.power(2)).set(~)
  killfeed <time=25> {string[distance]}.sqrt().*(2).round(2)
  do {string[oldX]}.set({exactX})
  do {string[oldZ]}.set({exactZ})
}

**Comment by ghost** [comment]
@kerbybit - Please read and review this issue.
LGTM
